class Alimento {
  String nombre;
  String tamanoporcion;
  double pesoengramo;
  double gramochos;

  Alimento({
    required this.nombre,
    required this.tamanoporcion,
    required this.pesoengramo,
    required this.gramochos,
  });
}

List<Alimento> alimentos = [
  Alimento(
    nombre: "Almojábana",
    tamanoporcion: "1/2 unidad mediana",
    pesoengramo: 50,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Almojábana",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 100,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Amaranto cocido",
    tamanoporcion: "4 cdas soperas cocidas",
    pesoengramo: 40,
    gramochos: 7.5,
  ),
  Alimento(
    nombre: "Amaranto cocido",
    tamanoporcion: "8 cdas soperas cocidas",
    pesoengramo: 80,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Arepa de maíz (Blanco o amarillo)",
    tamanoporcion: "1 unidad del tamaño de un CD de 1 cm de grosor",
    pesoengramo: 80,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Arepa paisa",
    tamanoporcion: "1 unidad del tamaño de un CD delgada",
    pesoengramo: 40,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Arepa redonda Pequeña",
    tamanoporcion: "1 unidad",
    pesoengramo: 30,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Arroz cocido",
    tamanoporcion: "1 cucharada sopera colmada",
    pesoengramo: 16.6,
    gramochos: 5,
  ),
  Alimento(
    nombre: "Arroz cocido",
    tamanoporcion: "2 cucharadas soperas colmadas",
    pesoengramo: 33,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Arroz cocido",
    tamanoporcion: "3 cucharadas soperas colmadas",
    pesoengramo: 50,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Arroz cocido",
    tamanoporcion: "4 cucharadas soperas colmadas",
    pesoengramo: 67,
    gramochos: 20,
  ),
  Alimento(
    nombre: "Arroz cocido",
    tamanoporcion: "5 cucharadas soperas colmadas",
    pesoengramo: 83,
    gramochos: 25,
  ),
  Alimento(
    nombre: "Arroz cocido",
    tamanoporcion: "6 cucharadas soperas colmadas",
    pesoengramo: 99.6,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Arroz cocido",
    tamanoporcion: "1/4 taza",
    pesoengramo: 38,
    gramochos: 11,
  ),
  Alimento(
    nombre: "Arroz cocido",
    tamanoporcion: "1/3 taza",
    pesoengramo: 50,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Arroz cocido",
    tamanoporcion: "1/2 taza",
    pesoengramo: 75,
    gramochos: 22,
  ),
  Alimento(
    nombre: "Arroz cocido",
    tamanoporcion: "1 taza",
    pesoengramo: 150,
    gramochos: 45,
  ),
  Alimento(
    nombre: "Avena cruda en hojuelas",
    tamanoporcion: "3 cdas soperas rasas",
    pesoengramo: 20,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Buñuelo",
    tamanoporcion: "1 unidad pequeña",
    pesoengramo: 40,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Buñuelo",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 80,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Cereal integral fitness (Nestlé)",
    tamanoporcion: "1 bolsa de tamaño personal",
    pesoengramo: 35,
    gramochos: 29,
  ),
  Alimento(
    nombre: "Cereal Corn Flakes",
    tamanoporcion: "1/2 taza",
    pesoengramo: 19,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Cebada perlada cocida",
    tamanoporcion: "3 cdas soperas rasas",
    pesoengramo: 30,
    gramochos: 23,
  ),
  Alimento(
    nombre: "Cuscus cocido",
    tamanoporcion: "1/2 taza",
    pesoengramo: 80,
    gramochos: 22.5,
  ),
  Alimento(
    nombre: "Cuscus cocido",
    tamanoporcion: "1 taza",
    pesoengramo: 160,
    gramochos: 45,
  ),
  Alimento(
    nombre: "Croissant (Mantequilla o queso)",
    tamanoporcion: "1 unidad pequeña",
    pesoengramo: 35,
    gramochos: 17,
  ),
  Alimento(
    nombre: "Croissant (Mantequilla o queso)",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 70,
    gramochos: 33,
  ),
  Alimento(
    nombre: "Empanada",
    tamanoporcion: "1/2 unidad mediana",
    pesoengramo: 26,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Empanada",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 52,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Envuelto de mazorca",
    tamanoporcion: "1/2 unidad mediana",
    pesoengramo: 50,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Envuelto de mazorca",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 100,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Fécula de maíz",
    tamanoporcion: "2 cdas soperas rasas",
    pesoengramo: 15,
    gramochos: 12,
  ),
  Alimento(
    nombre: "Fécula de maíz",
    tamanoporcion: "4 cdas soperas rasas",
    pesoengramo: 30,
    gramochos: 24,
  ),
  Alimento(
    nombre: "Galleta Soda (Saltina o integral)",
    tamanoporcion: "1 unidad",
    pesoengramo: 7,
    gramochos: 5,
  ),
  Alimento(
    nombre: "Galleta Soda (Saltina o integral)",
    tamanoporcion: "2 unidades",
    pesoengramo: 14,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Galleta Soda (Saltina o integral)",
    tamanoporcion: "3 unidades",
    pesoengramo: 20,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Granola",
    tamanoporcion: "1/2 taza",
    pesoengramo: 45,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Granola",
    tamanoporcion: "1/4 taza",
    pesoengramo: 23,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Harina de trigo",
    tamanoporcion: "3 cdas soperas rasas",
    pesoengramo: 20,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Maíz pira preparado",
    tamanoporcion: "1/2 taza",
    pesoengramo: 6,
    gramochos: 3,
  ),
  Alimento(
    nombre: "Maíz pira preparado",
    tamanoporcion: "1 taza",
    pesoengramo: 12,
    gramochos: 5,
  ),
  Alimento(
    nombre: "Mantecada/Ponque/Torta sin crema",
    tamanoporcion: "1 tajada mediana",
    pesoengramo: 63,
    gramochos: 35,
  ),
  Alimento(
    nombre: "Mazorca cocida",
    tamanoporcion: "1/2 unidad grande",
    pesoengramo: 75,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Mazorca cocida",
    tamanoporcion: "1 unidad grande",
    pesoengramo: 150,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Mazorca desgranada",
    tamanoporcion: "1 cda sopera rasa",
    pesoengramo: 15,
    gramochos: 3,
  ),
  Alimento(
    nombre: "Pan tajado blanco/centeno/integral",
    tamanoporcion: "1 tajada",
    pesoengramo: 30,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Pan blandito/rollo/manteq(panaderia)",
    tamanoporcion: "1 unidad pequeña",
    pesoengramo: 40,
    gramochos: 20,
  ),
  Alimento(
    nombre: "Pancake",
    tamanoporcion: "1 unidad del tamaño de un CD y 1/2 cm de grosor",
    pesoengramo: 30,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Pan perro",
    tamanoporcion: "1/2 unidad mediana",
    pesoengramo: 34,
    gramochos: 18,
  ),
  Alimento(
    nombre: "Pan perro",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 68,
    gramochos: 35,
  ),
  Alimento(
    nombre: "Pan hamburguesa",
    tamanoporcion: "1/2 unidad mediana",
    pesoengramo: 46,
    gramochos: 23,
  ),
  Alimento(
    nombre: "Pan hamburguesa",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 92,
    gramochos: 45,
  ),
  Alimento(
    nombre: "Pandebono",
    tamanoporcion: "1/2 unidad mediana",
    pesoengramo: 20,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Pandebono",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 40,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Pan de yuca",
    tamanoporcion: "1/2 unidad grande",
    pesoengramo: 35,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Pan de yuca",
    tamanoporcion: "1 unidad grande",
    pesoengramo: 70,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Pan pita",
    tamanoporcion: "1/2 unidad del tamaño de un CD",
    pesoengramo: 25,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Pan pita",
    tamanoporcion: "1 unidad del tamaño de un CD",
    pesoengramo: 50,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Pasta",
    tamanoporcion: "1/4 taza",
    pesoengramo: 34,
    gramochos: 11,
  ),
  Alimento(
    nombre: "Pasta",
    tamanoporcion: "1/3 taza",
    pesoengramo: 45,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Pasta",
    tamanoporcion: "1/2 taza",
    pesoengramo: 67,
    gramochos: 23,
  ),
  Alimento(
    nombre: "Pasta",
    tamanoporcion: "1 taza",
    pesoengramo: 134,
    gramochos: 45,
  ),
  Alimento(
    nombre: "Tostada/Calado",
    tamanoporcion: "1 unidad pequeña",
    pesoengramo: 13,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Tortilla mexicana",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 30,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Taco mexicano vacío",
    tamanoporcion: "1 unidad",
    pesoengramo: 13,
    gramochos: 8,
  ),
  Alimento(
    nombre: "Quinua cocida",
    tamanoporcion: "7 cdas soperas rasas",
    pesoengramo: 70,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Waffle",
    tamanoporcion: "1 unidad rectangular de 14 cm x 7 cm",
    pesoengramo: 45,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Arracacha",
    tamanoporcion: "1/2 unidad mediana",
    pesoengramo: 75,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Papa común",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 77,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Papa común",
    tamanoporcion: "1 unidad grande",
    pesoengramo: 150,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Papa criolla",
    tamanoporcion: "1 unidad pequeña",
    pesoengramo: 28,
    gramochos: 5,
  ),
  Alimento(
    nombre: "Papa criolla",
    tamanoporcion: "2 unidades pequeñas",
    pesoengramo: 56,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Papa criolla",
    tamanoporcion: "3 unidades pequeñas",
    pesoengramo: 84,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Papa francesa",
    tamanoporcion: "10 unidades delgadas",
    pesoengramo: 40,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Papa francesa",
    tamanoporcion: "20 unidades delgadas",
    pesoengramo: 80,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Plátano coli o Guinéo con cáscara",
    tamanoporcion: "1 unidad pequeña",
    pesoengramo: 145,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Plátano hartón",
    tamanoporcion: "1/4 unidad mediana o 2 tajadas medianas",
    pesoengramo: 50,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Plátano hartón",
    tamanoporcion: "1/2 unidad mediana o 4 tajadas medianas",
    pesoengramo: 100,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Ñame",
    tamanoporcion: "1 trozo mediano",
    pesoengramo: 67,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Yuca",
    tamanoporcion: "1 astilla pequeña",
    pesoengramo: 48,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Ouyuco/Chuguas",
    tamanoporcion: "7 unidades grandes",
    pesoengramo: 118,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Arveja seca cocida",
    tamanoporcion: "1/3 taza",
    pesoengramo: 37,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Arveja seca cocida",
    tamanoporcion: "1/2 taza",
    pesoengramo: 75,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Arveja seca cocida",
    tamanoporcion: "1 taza",
    pesoengramo: 150,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Frijol rojo cocido",
    tamanoporcion: "1/3 taza",
    pesoengramo: 37,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Frijol rojo cocido",
    tamanoporcion: "1/2 taza",
    pesoengramo: 75,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Frijol rojo cocido",
    tamanoporcion: "1 taza",
    pesoengramo: 150,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Garbanzo cocido",
    tamanoporcion: "1/3 taza",
    pesoengramo: 37,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Garbanzo cocido",
    tamanoporcion: "1/2 taza",
    pesoengramo: 75,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Garbanzo cocido",
    tamanoporcion: "1 taza",
    pesoengramo: 150,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Lenteja cocida",
    tamanoporcion: "1/3 taza",
    pesoengramo: 37,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Lenteja cocida",
    tamanoporcion: "1/2 taza",
    pesoengramo: 75,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Lenteja cocida",
    tamanoporcion: "1 taza",
    pesoengramo: 150,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Carve cocido",
    tamanoporcion: "1/2 taza",
    pesoengramo: 50,
    gramochos: 16,
  ),
  Alimento(
    nombre: "Carve cocido",
    tamanoporcion: "1 taza",
    pesoengramo: 100,
    gramochos: 33,
  ),
  Alimento(
    nombre: "Bienestarina",
    tamanoporcion: "1 cda sopera colmada",
    pesoengramo: 20,
    gramochos: 12,
  ),
  Alimento(
    nombre: "Colombiarina",
    tamanoporcion: "1 cda sopera colmada",
    pesoengramo: 11,
    gramochos: 7,
  ),
  Alimento(
    nombre: "Leche entera",
    tamanoporcion: "1/4 vaso",
    pesoengramo: 50,
    gramochos: 2.5,
  ),
  Alimento(
    nombre: "Leche entera",
    tamanoporcion: "1/3 vaso",
    pesoengramo: 67,
    gramochos: 3,
  ),
  Alimento(
    nombre: "Leche entera",
    tamanoporcion: "1/2 vaso",
    pesoengramo: 100,
    gramochos: 5,
  ),
  Alimento(
    nombre: "Leche entera",
    tamanoporcion: "1 vaso",
    pesoengramo: 200,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Leche semi/descremada",
    tamanoporcion: "1/4 vaso",
    pesoengramo: 50,
    gramochos: 2.5,
  ),
  Alimento(
    nombre: "Leche semi/descremada",
    tamanoporcion: "1/3 vaso",
    pesoengramo: 67,
    gramochos: 3,
  ),
  Alimento(
    nombre: "Leche semi/descremada",
    tamanoporcion: "1/2 vaso",
    pesoengramo: 100,
    gramochos: 5,
  ),
  Alimento(
    nombre: "Leche semi/descremada",
    tamanoporcion: "1 vaso",
    pesoengramo: 200,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Leche deslactosada",
    tamanoporcion: "1/4 vaso",
    pesoengramo: 50,
    gramochos: 2.5,
  ),
  Alimento(
    nombre: "Leche deslactosada",
    tamanoporcion: "1/3 vaso",
    pesoengramo: 67,
    gramochos: 3,
  ),
  Alimento(
    nombre: "Leche deslactosada",
    tamanoporcion: "1/2 vaso",
    pesoengramo: 100,
    gramochos: 5,
  ),
  Alimento(
    nombre: "Leche deslactosada",
    tamanoporcion: "1 vaso",
    pesoengramo: 200,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Leche en polvo entera",
    tamanoporcion: "1 cda colmada",
    pesoengramo: 9,
    gramochos: 3,
  ),
  Alimento(
    nombre: "Leche en polvo entera",
    tamanoporcion: "2 cdas colmadas",
    pesoengramo: 18,
    gramochos: 6,
  ),
  Alimento(
    nombre: "Leche en polvo entera",
    tamanoporcion: "3 cdas colmadas",
    pesoengramo: 27,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Yogurt finesse",
    tamanoporcion: "1/2 vaso",
    pesoengramo: 90,
    gramochos: 5.5,
  ),
  Alimento(
    nombre: "Yogurt finesse",
    tamanoporcion: "1 vaso",
    pesoengramo: 180,
    gramochos: 11,
  ),
  Alimento(
    nombre: "Yogurt slight Colanta",
    tamanoporcion: "1/2 vaso",
    pesoengramo: 100,
    gramochos: 6,
  ),
  Alimento(
    nombre: "Yogurt slight Colanta",
    tamanoporcion: "1 vaso",
    pesoengramo: 200,
    gramochos: 12,
  ),
  Alimento(
    nombre: "Yogurt Benecol",
    tamanoporcion: "1 unidad",
    pesoengramo: 100,
    gramochos: 4,
  ),
  Alimento(
    nombre: "Avena Finesse",
    tamanoporcion: "1 vaso",
    pesoengramo: 250,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Yogurt pasco (Tipo postre- sin azúcar)",
    tamanoporcion: "1 vaso",
    pesoengramo: 150,
    gramochos: 5,
  ),
  Alimento(
    nombre: "Yogurt San fernando Light",
    tamanoporcion: "1 vaso",
    pesoengramo: 160,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Yogurt Slim Natural 'Doña Leche'",
    tamanoporcion: "1 vaso",
    pesoengramo: 200,
    gramochos: 12,
  ),
  Alimento(
    nombre: "Yogurt Dietético Coolechera",
    tamanoporcion: "1 vaso",
    pesoengramo: 150,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Helado Light Mimos",
    tamanoporcion: "1 bola",
    pesoengramo: 70,
    gramochos: 18,
  ),
  Alimento(
    nombre: "Paleta light Robin Hood",
    tamanoporcion: "1 unidad",
    pesoengramo: 60,
    gramochos: 20,
  ),
  Alimento(
    nombre: "Arroz con pollo",
    tamanoporcion: "1/2 taza",
    pesoengramo: 85,
    gramochos: 19,
  ),
  Alimento(
    nombre: "Arroz con pollo",
    tamanoporcion: "1 taza",
    pesoengramo: 170,
    gramochos: 38,
  ),
  Alimento(
    nombre: "Pizza (Zenú)",
    tamanoporcion: "1 tajada mediana",
    pesoengramo: 130,
    gramochos: 35,
  ),
  Alimento(
    nombre: "Lasaña (Zenú)",
    tamanoporcion: "1 porción mediana",
    pesoengramo: 445,
    gramochos: 47,
  ),
  Alimento(
    nombre: "Hamburguesa (Pan Bimbo)",
    tamanoporcion: "1/2 unidad mediana",
    pesoengramo: 105,
    gramochos: 23,
  ),
  Alimento(
    nombre: "Hamburguesa (Pan Bimbo)",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 210,
    gramochos: 45,
  ),
  Alimento(
    nombre: "Nuggets de pollo (Zenú)",
    tamanoporcion: "5 unidades",
    pesoengramo: 85,
    gramochos: 14,
  ),
  Alimento(
    nombre: "Aborrajado sin bocadillo (Kalisto)",
    tamanoporcion: "1 unidad pequeña",
    pesoengramo: 112,
    gramochos: 20,
  ),
  Alimento(
    nombre: "Tamal santandereano sin hojas",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 200,
    gramochos: 75,
  ),
  Alimento(
    nombre: "Tamal tolimense sin hojas",
    tamanoporcion: "1 unidad mediana",
    pesoengramo: 325,
    gramochos: 60,
  ),
  Alimento(
    nombre: "Salvado de trigo",
    tamanoporcion: "5 cdas rasas",
    pesoengramo: 50,
    gramochos: 32,
  ),
  Alimento(
    nombre: "All Bran",
    tamanoporcion: "3 cdas",
    pesoengramo: 20,
    gramochos: 15,
  ),
  Alimento(
    nombre: "All Bran",
    tamanoporcion: "6 cdas",
    pesoengramo: 40,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Tostada Bimbo",
    tamanoporcion: "1 unidad",
    pesoengramo: 15.5,
    gramochos: 10.5,
  ),
  Alimento(
    nombre: "Tostada Bimbo",
    tamanoporcion: "2 unidades",
    pesoengramo: 31,
    gramochos: 21,
  ),
  Alimento(
    nombre: "Paleta en agua (Mimos Light)",
    tamanoporcion: "1 unidad",
    pesoengramo: 70,
    gramochos: 4,
  ),
  Alimento(
    nombre: "Papas fritas (Margarita)",
    tamanoporcion: "1 paquete",
    pesoengramo: 25,
    gramochos: 12,
  ),
  Alimento(
    nombre: "Rosquitas (Cronch)",
    tamanoporcion: "1 paquete",
    pesoengramo: 19,
    gramochos: 13,
  ),
  Alimento(
    nombre: "Tajaditas de plátano verde (Natuchips)",
    tamanoporcion: "1 paquete",
    pesoengramo: 28,
    gramochos: 20,
  ),
  Alimento(
    nombre: "Instacrem",
    tamanoporcion: "1 sobre",
    pesoengramo: 4,
    gramochos: 3,
  ),
  Alimento(
    nombre: "Chocolyne",
    tamanoporcion: "1 pastilla",
    pesoengramo: 10,
    gramochos: 3,
  ),
  Alimento(
    nombre: "Chocolyne/ Choco express",
    tamanoporcion: "1 cdita polvo",
    pesoengramo: 4,
    gramochos: 2,
  ),
  Alimento(
    nombre: "Maní",
    tamanoporcion: "1 paquete",
    pesoengramo: 50,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Marañón",
    tamanoporcion: "1 paquete",
    pesoengramo: 40,
    gramochos: 10,
  ),
  Alimento(
    nombre: "Mezcla de nueces",
    tamanoporcion: "1 paquete",
    pesoengramo: 50,
    gramochos: 11,
  ),
  Alimento(
    nombre: "Barra granola (Sport Lyne)",
    tamanoporcion: "1 unidad",
    pesoengramo: 23,
    gramochos: 16,
  ),
  Alimento(
    nombre: "Arequipe de Antaño Light",
    tamanoporcion: "2 cdas soperas rasas",
    pesoengramo: 25,
    gramochos: 13.5,
  ),
  Alimento(
    nombre: "Carne de pollo (Asada o cocida)",
    tamanoporcion: "1/5 parte de libra",
    pesoengramo: 100,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Carne de cerdo (Asada o cocida)",
    tamanoporcion: "1/5 parte de libra",
    pesoengramo: 100,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Carne de res (Asada o cocida)",
    tamanoporcion: "1/5 parte de libra",
    pesoengramo: 100,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Hígado (Asado o cocido)",
    tamanoporcion: "1/5 parte de libra",
    pesoengramo: 100,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Chicharrón asado o cocido",
    tamanoporcion: "1/5 parte de libra",
    pesoengramo: 100,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Harina para apanado Sin azúcar",
    tamanoporcion: "1 cucharada sopera",
    pesoengramo: 10,
    gramochos: 6,
  ),
  Alimento(
    nombre: "Morcilla",
    tamanoporcion: "1 unidad",
    pesoengramo: 63,
    gramochos: 17,
  ),
  Alimento(
    nombre: "Jamón bajo en grasa",
    tamanoporcion: "2 tajadas",
    pesoengramo: 41,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Salchicha baja en grasa",
    tamanoporcion: "2 unidades",
    pesoengramo: 50,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Mortadela",
    tamanoporcion: "2 tajadas",
    pesoengramo: 38,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Salchichón",
    tamanoporcion: "2 tajadas",
    pesoengramo: 50,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Queso",
    tamanoporcion: "1 tajada",
    pesoengramo: 30,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Queso parmesano (Bajo en grasa)",
    tamanoporcion: "1 cucharada sopera",
    pesoengramo: 10,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Quesito",
    tamanoporcion: "1 tajada",
    pesoengramo: 30,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Queso mozzarella (Bajo en grasa)",
    tamanoporcion: "2 tajadas",
    pesoengramo: 34,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Cuajada",
    tamanoporcion: "1 tajada",
    pesoengramo: 30,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Huevo",
    tamanoporcion: "1 unidad",
    pesoengramo: 67,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Café",
    tamanoporcion: "1 cucharada",
    pesoengramo: 5,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Aromática",
    tamanoporcion: "1 bolsita",
    pesoengramo: 1.2,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Consomé",
    tamanoporcion: "1 taza",
    pesoengramo: 240,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Sopa (1 taza de verduras + 1 papa criolla)",
    tamanoporcion: "1 taza",
    pesoengramo: 240,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Caldo (papa pequeña + huevo)",
    tamanoporcion: "1 taza",
    pesoengramo: 240,
    gramochos: 15,
  ),
  Alimento(
    nombre: "Cremas (1 taza de verduras + 1/2 vaso con leche + 1 papa pequeña)",
    tamanoporcion: "1 taza",
    pesoengramo: 240,
    gramochos: 30,
  ),
  Alimento(
    nombre: "Aceite de canola",
    tamanoporcion: "1 cucharada sopera",
    pesoengramo: 5,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Aceite de girasol",
    tamanoporcion: "1 cucharada sopera",
    pesoengramo: 5,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Aceite de oliva",
    tamanoporcion: "1 cucharada sopera",
    pesoengramo: 5,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Mantequilla sin sal",
    tamanoporcion: "1 cucharada dulcera rasa",
    pesoengramo: 5,
    gramochos: 0,
  ),
  Alimento(
    nombre: "Margarina line (reducida 25%)",
    tamanoporcion: "1 cucharada sopera rasa",
    pesoengramo: 10,
    gramochos: 0,
  ),
];
